import { NextResponse } from "next/server";

// HealthAI Patient Dashboard — Projects API Route
// Auto-generated by Backend Agent Viktor Vance @ AutoScale AI

// In-memory store for demo (replace with Prisma in production)
const projects = [
  {
    id: "proj_1",
    title: "HealthAI Patient Dashboard",
    description: "A real-time patient monitoring dashboard with AI-powered diagnostics, appointment scheduling, prescr",
    status: "ACTIVE",
    budget: 24000,
    createdAt: new Date().toISOString(),
  }
];

export async function GET() {
  return NextResponse.json(projects);
}

export async function POST(req: Request) {
  const body = await req.json();
  const newProject = {
    id: `proj_${Date.now()}`,
    ...body,
    status: "ACTIVE",
    createdAt: new Date().toISOString(),
  };
  projects.push(newProject);
  return NextResponse.json(newProject, { status: 201 });
}